services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: always
    volumes:
      - "./qdrant_storage:/qdrant/storage:z"
    ports:
      - "6333:6333"
      - "6334:6334"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 256M
